---
# handlers do not inherit the "become" in main.yml

- name: Reload Apache
  ansible.builtin.systemd_service:
    name: httpd
    state: reloaded
  become: true

- name: Restart Apache
  ansible.builtin.systemd_service:
    name: httpd
    state: restarted
  become: true
