---
# adds one virtualhost
# change to handle a list?
#
- name: Install packages
  ansible.builtin.yum: 
    name: 
    - httpd
    - mod_ssl
    state: latest 

- name: Start and enable service httpd
  ansible.builtin.service:
    name: httpd
    enabled: yes
    state: started

# SELinux - this inherits file type "httpd_sys_content_t"
- name: add another document root
  ansible.builtin.file:
    path: "/var/www/{{ apache_host }}"
    state: directory
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: '2775'

- name: Copy index test page
  ansible.builtin.template:
    src: index.html.j2
    dest: "/var/www/{{ apache_host }}/index.html"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: '0664'

- name: add a plaintext Apache virtualHost
  ansible.builtin.template:
    src: virtualhost.conf.j2
    dest: "/etc/httpd/conf.d/{{ apache_host }}.conf"
  notify: Reload Apache

- name: add an encrypted Apache virtualHost
  ansible.builtin.template:
    src: virtualhost.ssl.conf.j2
    dest: "/etc/httpd/conf.d/{{ apache_host }}.ssl.conf"
  # notify: Restart Apache
  notify: Reload Apache

- name: add the server certificate containing the public key
  ansible.builtin.copy: 
    src: virtualhost.crt
    dest: "/etc/pki/tls/certs/{{ apache_host }}.pem"
  when: use_my_cert

- name: add the matching private key
  ansible.builtin.copy: 
    src: virtualhost.key
    dest: "/etc/pki/tls/private/{{ apache_host }}.key"
    mode: 0640
  when: use_my_cert

# use /etc/pki/ca-trust/ and update-ca-trust?

- name: permit traffic in default zone
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: yes
    immediate: yes
    state: enabled
  loop:
  - http
  - https

