---
# tasks file
# A simpler version of Josh Swanson's far superior work.
# https://www.redhat.com/en/blog/installing-gitlab-ce-rhel-9
- name: install prerequisites
  ansible.builtin.yum:
    name:
      - yum-utils
      - policycoreutils
      - openssh-server
      - openssh-clients
      - postfix
  register: packages_installed

- name: start/enable services
  ansible.builtin.systemd:
    name: "{{ service }}"
    enabled: yes
    state: started
  loop_control:
    loop_var: service
  loop:
    - sshd
    - postfix
  when:
    - packages_installed.changed

- name: push gitlab repo file
  ansible.builtin.copy:
    src: gitlab.repo
    dest: "/etc/yum.repos.d/gitlab_gitlab-ce.repo"
    owner: root
    group: root
    mode: '0644'
  register: repo_file_pushed

- name: clear yum cache
  ansible.builtin.shell:
    cmd: yum clean all
  when:
    - repo_file_pushed.changed

- name: install gitlab
  ansible.builtin.yum:
    name: gitlab-ce
  environment:
    EXTERNAL_URL: "https://{{ inventory_hostname }}"
    GITLAB_ROOT_PASSWORD: "{{ gitlab_admin_password }}"
  notify:
    - setup_api_token
  ignore_errors: true

# !!! self-signed certificate
# change this configuration
#   /etc/gitlab/gitlab.rb
#   nginx['ssl_certificate'] = "/etc/gitlab/ssl/#{node['fqdn']}.crt"
#   nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/#{node['fqdn']}.key"
# to
#   nginx['ssl_certificate'] = "/etc/pki/tls/certs/git.source.example.com.pem"
#   nginx['ssl_certificate_key'] = "/etc/pki/tls/private/git.source.example.com.key"

- name: back up original gitlab config file
  ansible.builtin.copy:
    src: /etc/gitlab/gitlab.rb
    dest: /etc/gitlab/gitlab.rb-orig
    remote_src: true

- name: push new gitlab config file
  ansible.builtin.copy:
    src: gitlab.rb
    dest: /etc/gitlab/gitlab.rb

# !!! not done?
# https://github.com/geerlingguy/ansible-role-gitlab/blob/master/tasks/main.yml#L49C1-L56C21
# Running "gitlab-ctl reconfigure" may be required.
# Start and configure GitLab. Sometimes the first run fails, but after that,
# restarts fix problems, so ignore failures on this run.
- name: Reconfigure GitLab (first run).
  command:
    cmd: gitlab-ctl reconfigure
    #creates=/var/opt/gitlab/bootstrapped
  #failed_when: false

# !!! done? 
# try logging in with 
#   url: "https://{{ inventory_hostname }}"
#   user: root
#   password: "{{ gitlab_admin_password }}"
