---
# tasks file

- name: Create node_exporter system group
  ansible.builtin.group:
    name: node_exporter
    system: true
    state: present

- name: Create node_exporter system user
  ansible.builtin.user:
    name: node_exporter
    system: true
    shell: "/usr/sbin/nologin"
    group: node_exporter
    createhome: false
    # home: "{{ node_exporter_data_dir }}"


# Open firewall port 9100 for node_exporter
- name: Permit service traffic
  ansible.posix.firewalld:
    port: 9100/tcp
    immediate: yes
    permanent: yes
    state: enabled

# systemd
- name: Add a new systemd service unit
  ansible.builtin.template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart node_exporter
#
- name: Tell systemd about the new unit file
  systemd:
    daemon_reload: yes


# https://docs.ansible.com/ansible/latest/collections/community/general/seport_module.html
- name: Allow node_exporter to bind to port in SELinux
  community.general.seport:
    ports: 9100
    proto: tcp
    setype: http_port_t
    state: present
