---
# tasks file

- name: Create node_exporter system group
  ansible.builtin.group:
    name: node_exporter
    system: true
    state: present

- name: Create node_exporter system user
  ansible.builtin.user:
    name: node_exporter
    system: true
    shell: "/usr/sbin/nologin"
    group: node_exporter
    createhome: false
    home: "{{ node_exporter_data_dir }}"


# Open firewall port 9091 for prometheus
# Not the usual 9090, that's used by cockpit
- name: permit service traffic
  ansible.posix.firewalld:
    port: 9091/tcp
    immediate: yes
    permanent: yes
    state: enabled

# systemd
- name: Add a new systemd service unit
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart prometheus
#
- name: Tell systemd about the new unit file
  systemd:
    daemon_reload: yes

- name: Install SELinux dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ prometheus_selinux_packages }}"
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2

# https://docs.ansible.com/ansible/latest/collections/community/general/seport_module.html
- name: Allow prometheus to bind to port in SELinux
  community.general.seport:
    ports: "{{ prometheus_web_listen_address.split(':')[1] }}"
    proto: tcp
    setype: http_port_t
    state: present
