---
# tasks file for antora_generator
#
- name: Who am I
  ansible.builtin.debug:
    verbosity: 1
    var: ansible_facts['user_id']

- name: Install required packages
  ansible.builtin.yum:
    name:
      - git
      - httpd
      - tar
    state: latest
  become: true

- name: Install nvm
  ansible.builtin.include_tasks: nvm.yml
- name: Install node
  ansible.builtin.include_tasks: node.yml
- name: Install antora
  ansible.builtin.include_tasks: antora.yml
- name: Turn asciidoctor into HTML
  ansible.builtin.include_tasks: content.yml

- name: Generate website content
  ansible.builtin.shell:
    cmd: antora antora-playbook.yml
  args:
    chdir: "~/docs-site"
  register: r_antora
  changed_when: true

- name: Display result
  ansible.builtin.debug:
    verbosity: 1
    var: r_antora
