---
# tasks file

# A simpler version of
# https://github.com/cloudalchemy/ansible-prometheus/blob/master/tasks/install.yml

# A fancier version of 
# https://prometheus.io/docs/prometheus/latest/getting_started/#downloading-and-running-prometheus


- name: "Download prometheus from {{ install_file_source }} to {{ download_dir }}/{{ install_file }}"
  ansible.builtin.get_url:
    url: "{{ install_file_source }}"
    dest: "{{ download_dir }}/{{ install_file }}"
    checksum: "sha256:{{ sha256_checksum }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  check_mode: false

- name: Unpack prometheus binaries
  ansible.builtin.unarchive:
    src: "{{ download_dir }}/{{ install_file }}"
    remote_src: true
    dest: "{{ download_dir }}"
    creates: "{{ download_dir }}/{{ archive_dir }}/prometheus"
  check_mode: false

- name: Propagate official prometheus and promtool binaries
  ansible.builtin.copy:
    src: "{{ download_dir }}/{{ archive_dir }}/{{ item }}"
    dest: "{{ prometheus_binary_dir }}/{{ item }}"
    mode: "0755"
    owner: root
    group: root
  with_items:
    - prometheus
    - promtool
  notify:
    - restart prometheus

- name: Propagate official console templates
  ansible.builtin.copy:
    src: "{{ download_dir }}/{{ archive_dir }}/{{ item }}/"
    dest: "{{ prometheus_config_dir }}/{{ item }}/"
    mode: "0644"
    owner: root
    group: root
  with_items:
    - console_libraries
    - consoles
  notify:
    - restart prometheus
