---
# tasks file

# A simpler version of
# https://github.com/cloudalchemy/ansible-prometheus/blob/master/tasks/install.yml

# A fancier version of 
# https://prometheus.io/docs/prometheus/latest/getting_started/#downloading-and-running-prometheus

- name: Create prometheus system group
  ansible.builtin.group:
    name: prometheus
    system: true
    state: present

- name: Create prometheus system user
  ansible.builtin.user:
    name: prometheus
    system: true
    shell: "/usr/sbin/nologin"
    group: prometheus
    createhome: false
    home: "{{ prometheus_db_dir }}"

- name: Create prometheus data directory
  ansible.builtin.file:
    path: "{{ prometheus_db_dir }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: "0755"

- name: Create prometheus configuration directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: prometheus
    mode: "0770"
  with_items:
    - "{{ prometheus_config_dir }}"
    - "{{ prometheus_config_dir }}/rules"
    - "{{ prometheus_config_dir }}/file_sd"

# Open firewall port 9091 for prometheus
# Not the usual 9090, that's used by cockpit
- name: permit service traffic
  ansible.posix.firewalld:
    port: 9091/tcp
    immediate: yes
    permanent: yes
    state: enabled

- name: create systemd service unit
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart prometheus

- name: Install SELinux dependencies
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ prometheus_selinux_packages }}"
  register: _install_packages
  until: _install_packages is succeeded
  retries: 5
  delay: 2

# https://docs.ansible.com/ansible/latest/collections/community/general/seport_module.html
- name: Allow prometheus to bind to port in SELinux
  community.general.seport:
    ports: "{{ prometheus_web_listen_address.split(':')[1] }}"
    proto: tcp
    setype: http_port_t
    state: present
